<?php

namespace Domain\Services;

use Infrastructure\Repositories\MenuItemRepository;
use Infrastructure\Repositories\MenuRepository;
use Infrastructure\Repositories\SoundRepository;

/**
 * Class MenuService
 * @package Domain\Services
 */
class MenuService extends AbstractService
{
    /**
     * @var MenuItemRepository
     */
    protected $menuitemRepository;

    /**
     * SoundService constructor.
     * @param MenuRepository $menuRepository
     * @param MenuItemRepository $menuItemRepository
     */
    public function __construct(MenuRepository $menuRepository, MenuItemRepository $menuItemRepository)
    {
        $this->menuitemRepository = $menuItemRepository;
        $this->repository = $menuRepository;
    }

    /**
     * @param array $match
     * @param array $params
     * @return \Illuminate\Database\Eloquent\Model
     */
    public function updateOrCreateItem(array $match, array $params)
    {
        $this->repository = $this->menuitemRepository;
        return parent::updateOrCreate($match, $params); // TODO: Change the autogenerated stub
    }
}